ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "AssistantId" UUID;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "CheckInTime" TIMESTAMP;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "ConsultationStartedAt" TIMESTAMP;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "DoctorJoinedAt" TIMESTAMP;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "ConsultationEndedAt" TIMESTAMP;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "DurationInMinutes" INTEGER;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "NotificationsSentCount" INTEGER DEFAULT 0;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "LastNotificationSentAt" TIMESTAMP;
ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "LastActivityAt" TIMESTAMP;
